=== mayur13walke/mylabtest/awp-phpcode/day5/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="employee" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="eno" type="xs:int"/>
        <xs:element name="ename" type="xs:string"/>
        <xs:element name="eaddress" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mayur13walke/mylabtest/awp-phpcode/day5/employees1.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                        xsi:noNamespaceSchemaLocation="/home/mahesh/Desktop/KDAC-AWP/Day5/employee.xsd">
  <employee>
    <eno>100</eno>  
   <ename> mahesh </ename>
   <eaddress>pune</eaddress>
  </employee>
  
  <employee>
    <eno> 200 </eno>  
   <ename> nilesh </ename>
   <eaddress>panji</eaddress>
  </employee>
  
  
  <employee>
    <eno> 200 </eno>  
   <ename> rahul </ename>
   <eaddress>mumbai</eaddress>
  </employee>
  
  
</employees>
